### ISSUE TITLE
What wifi card does this efi support ? any plan fror ventura ?

### ISSUE THREAD

**Issue by HiR3x** [emikodes/Lenovo-Thinkpad-L470-Opencore-EFI#1]

**Comment by emikodes** [comment]
Hi! This EFI should also work with Mac OS Ventura. Haven't personally tested because i don't have this laptop anymore.
Works with both Intel Wifi Cards available for this model:
• Intel Dual Band Wireless-AC 8260, Wi-Fi 2x2 802.11ac + BT4.1, M.2 card
• Intel Dual Band Wireless-AC 8265, Wi-Fi 2x2 802.11ac + BT4.1, M.2 card
